name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the forked repository
        uses: actions/checkout@v3
        with:
          ref: master # Updated to master branch

      - name: Setup Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Add Upstream remote
        run: git remote add upstream https://github.com/rustdesk/rustdesk.git

      - name: Fetch Upstream changes
        run: git fetch upstream

      - name: Merge Upstream changes
        run: git merge upstream/master --allow-unrelated-histories

      - name: Push changes to fork
        run: git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
